### ISSUE TITLE
check UBSAN issues from examples

### ISSUE THREAD

**Issue by mpadge** [ropensci/bikedata#100]
Last CRAN flag arose from UBSAN issues from one of the examples. Do a full UBSAN check on all examples to ensure that [this commit](https://github.com/ropensci/bikedata/commit/6281cd0eb153e366073a06b401522b804808f04d) for #95 has fixed everything.

**Comment by mpadge** [comment]
Output from `rocker/r-devel-ubsan-clang`:
```
=================================================================
==40291==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3096 byte(s) in 3 object(s) allocated from:
    #0 0x4f5512 in operator new[](unsigned long) (/usr/local/lib/R/bin/exec/R+0x4f5512)
    #1 0x7f197375008c in tbb::internal::task_stream<3>::initialize(unsigned int) /tmp/RtmpYFsp72/R.INSTALL679526f0d6e3/RcppParallel/src/tbb/build/lib_release/../../src/tbb/task_stream.h:94:28
    #2 0x7f197375008c in tbb::internal::arena::arena(tbb::internal::market&, unsigned int, unsigned int) /tmp/RtmpYFsp72/R.INSTALL679526f0d6e3/RcppParallel/src/tbb/build/lib_release/../../src/tbb/arena.cpp:225:30

SUMMARY: AddressSanitizer: 3096 byte(s) leaked in 3 allocation(s).
```
Just the usual `RcppParallel` leak, but no other undefined behaviour, so looks like this can be closed ready for re-submission.
